### ISSUE TITLE
why do down_channel twice?

### ISSUE THREAD

**Issue by kleinzcy** [latentgnn/LatentGNN-V1-PyTorch#2]
Congratulation and thanks to your work!

I read your paper and code. It is a nice work! But it puzzled me why you down_channel twice. In my understanding, the part dataflow is conv_feature(B\*C\*H\*W)-->v2l_conv_feature(B\*C/4\*H\*W)-->v2l_graph_adj(B\*d\*H\*W)(d is latent dimension).  Why not directly down conv_feature's channel to d?

**Comment by tonysy** [comment]
The first one is used to reduce the feature channel, and the second one is used to generate the adjacency matrix for visible-to-latent propagation. Actually, you can also generate the adjacency matrix from the conv feature directly. If you have any progress, welcome to the report the performance.
